-- MySQL Script generated by MySQL Workbench
-- Mon Jan  8 17:09:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Street_Art_Hunterz
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Street_Art_Hunterz` ;

-- -----------------------------------------------------
-- Schema Street_Art_Hunterz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Street_Art_Hunterz` DEFAULT CHARACTER SET utf8 ;
USE `Street_Art_Hunterz` ;

-- -----------------------------------------------------
-- Table `Street_Art_Hunterz`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Street_Art_Hunterz`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(12) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `registration_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `score` INT NOT NULL,
  `admin` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Street_Art_Hunterz`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Street_Art_Hunterz`.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `Work_id` INT NOT NULL,
  `image` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_location_Work1_idx` (`Work_id` ASC) VISIBLE,
  CONSTRAINT `fk_location_Work1`
    FOREIGN KEY (`Work_id`)
    REFERENCES `Street_Art_Hunterz`.`Work` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Street_Art_Hunterz`.`Work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Street_Art_Hunterz`.`Work` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `longitude` INT NOT NULL,
  `latitude` INT NOT NULL,
  `image` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  `entry` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `is_validate` TINYINT(0) NOT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Work_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Work_location1_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_Work_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Street_Art_Hunterz`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Work_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `Street_Art_Hunterz`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Street_Art_Hunterz`.`Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Street_Art_Hunterz`.`Artist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(12) NOT NULL,
  `city` VARCHAR(120) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Street_Art_Hunterz`.`Artist_Work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Street_Art_Hunterz`.`Artist_Work` (
  `Artist_id` INT NOT NULL,
  `Work_id` INT NOT NULL,
  PRIMARY KEY (`Artist_id`, `Work_id`),
  INDEX `fk_Artist_has_Work_Work1_idx` (`Work_id` ASC) VISIBLE,
  INDEX `fk_Artist_has_Work_Artist1_idx` (`Artist_id` ASC) VISIBLE,
  CONSTRAINT `fk_Artist_has_Work_Artist1`
    FOREIGN KEY (`Artist_id`)
    REFERENCES `Street_Art_Hunterz`.`Artist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artist_has_Work_Work1`
    FOREIGN KEY (`Work_id`)
    REFERENCES `Street_Art_Hunterz`.`Work` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
